# - name: Logstash 
#   hosts: localhost
#   become: yes
#   roles:
#   - role: /home/ubuntu/logstash-role/logstash-tool

---
- hosts: tag_data_logstash
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
    - logstash-tool
